version: "3"

networks:
  my-net:

services:
  some-mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: pw
    networks:
      - my-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5000:80
    environment:
      PMA_HOST: some-mysql
    networks:
      - my-net